.env.travis
.travis.yml
app/Providers/AppServiceProvider.php

Does what it says on the tin. At least, that's the hope. We'll see!

Setup Travis, closing #11

---

resources/js/components/StatsBar.vue
resources/views/layouts/app.blade.php

Refs #6 
Provide a prop hostname variable from layout.app to StatBar component.

Pass dynamic hostname to StatusBar component

---

README.md
app/Http/Controllers/System/GroupsController.php
package-lock.json
package.json
resources/js/app.js
resources/js/components/System/GroupEditor.vue
resources/js/components/System/GroupItem.vue
resources/js/components/System/Groups.vue
resources/js/components/System/Users.vue
resources/js/store/index.js
resources/js/store/modules/System/Group.js
resources/views/layouts/system.blade.php
routes/api.php
tests/Feature/CreateSystemGroupTest.php
tests/Feature/DeleteSystemGroupTest.php
tests/Feature/UpdateSystemGroupTest.php

Adds a new sidebar with support for creating, renaming and deleting groups (see #19) as well as changing their Group IDs.
Also refactors groups to use VueX and fixes a couple other bits with filters, listing etc.

Basic group editing

---

app/Providers/AppServiceProvider.php
app/StatsBar.php
resources/js/components/StatsBar.vue
resources/views/layouts/app.blade.php

Finally sets hostname to the real machine name instead of 'localhost' to
resolve #21

Set distro/hostname from [os,lsb]-release files

---

README.md
app/Http/Controllers/System/GroupsController.php
app/Http/Controllers/System/UsersController.php
resources/js/components/MainMenu.vue
resources/js/components/System/GroupEditor.vue
resources/js/components/System/Groups.vue
resources/js/components/System/Menu.vue
resources/js/components/System/UserEditor.vue
resources/js/components/System/UserItem.vue
resources/js/components/System/Users.vue
resources/js/store/modules/System/Group.js
resources/js/store/modules/System/User.js

Adds secondary groups to the user editor with ability to add/remove items, and the same for the members list in the group editor.

Add ability to update User/Group memberships

---

.travis.yml
app/Http/Controllers/SiteController.php
app/Rules/Domain.php
composer.json
composer.lock
tests/Feature/CreateSiteTest.php
tests/Unit/DomainValidationTest.php

Tests to make sure that all valid domains will be accepted, and those that
are too long will be rejected. Updates SiteController's store and update
methods to use the new Domain rule too.
Fixes #56

Add domain validation rule with tests

---

CHANGELOG.md
resources/js/components/System/Groups.vue
resources/js/components/System/UserItem.vue
resources/js/components/System/Users.vue
resources/js/layouts/Servidor.vue
resources/js/pages/Auth/Login.vue
resources/js/pages/Files/Browser.vue
resources/js/pages/Files/Editor.vue
resources/js/pages/Sites.vue
resources/js/pages/Sites/List.vue
resources/views/layouts/app.blade.php
resources/views/layouts/login.blade.php
resources/views/servidor.blade.php

Fixes padding on smaller browser widths and cleans up a few unnecessary wrapper divs - among other things.

UI Cleanup

---

CHANGELOG.md
resources/js/app.js
resources/js/pages/Auth/Login.vue
resources/js/store/modules/Auth.js

Fix forcing of login when token is invalidated

---

CHANGELOG.md
resources/js/components/System/Groups.vue
resources/js/components/System/Users.vue
resources/js/store/modules/System/User.js

Fixes the following issues with the system users and groups:
Fixes #122, fixes #123

Fix various errors preventing System User/Group creation

---

resources/js/pages/Sites.vue
resources/js/store/modules/Site.js

Redirect to editor after application is created

---

resources/js/components/System/GroupItem.vue

Fix issue with group's users aren't updated in the list.

---

app/Http/Controllers/System/UsersController.php
tests/Feature/Api/System/Users/UpdateUserTest.php

Fix issue with adding group to user

---

.gitignore
CHANGELOG.md
resources/js/app.js
resources/js/components/Files/Browser/FileList.vue
resources/js/components/Sites/Editor.vue
resources/js/components/Sites/SiteItem.vue
resources/js/components/System/GroupEditor.vue
resources/js/components/System/Groups.vue
resources/js/components/System/UserEditor.vue
resources/js/components/System/Users.vue
resources/js/layouts/Servidor.vue
resources/js/pages/Databases.vue
resources/js/pages/Files/Editor.vue
resources/js/pages/Sites.vue
resources/js/pages/Sites/Detail.vue
resources/js/plugins/darkmode/index.js
resources/sass/app.scss
resources/sass/components/_themeswitcher.scss
resources/sass/core.scss
resources/sass/themes/darkmode-custom.scss
resources/sass/themes/darkmode.scss
resources/views/layouts/app.blade.php
webpack.mix.js

because computers suck when you wake up at 3am.

Add dark mode

---

.phpmd.xml
app/Exceptions/System/UserNotFoundException.php
app/Exceptions/System/UserNotModifiedException.php
app/Exceptions/System/UserSaveException.php
app/Http/Controllers/System/UsersController.php
app/Http/Requests/System/SaveUser.php
app/Rules/ValidLinuxUser.php
app/System/User.php
app/System/Users/LinuxUser.php
tests/Feature/Api/System/Users/CreateUserTest.php
tests/Feature/Api/System/Users/TestCase.php

This is a complete refactor of the `SystemUsers` controller with a view to supporting user creation as part of the "New Site" process. See each individual commit for more details.
This provides the first half of #141, where groups still need a refactor before it can be closed.
It also goes a large way to getting #170 off the ground finally.

System Users refactor

---

CHANGELOG.md
app/FileManager/FileManager.php
app/Http/Controllers/SiteController.php
app/Site.php
app/System/User.php
app/System/Users/LinuxUser.php
database/migrations/2020_01_23_032749_add_user_column_to_sites_table.php
resources/js/components/Sites/Editor.vue
resources/js/pages/Sites/Detail.vue
resources/js/store/modules/Site.js
resources/sass/themes/darkmode-custom.scss

Adds support to the LinuxUser class for setting home directories which can be used from the SiteController when saving a project. To back that up, the System\User class now also supports creating custom instances providing your own LinuxUser instance.
Users are now linked to sites, with details about it shown on the project overview.
Closes #201.

Add option to create a user when saving a project

---

CHANGELOG.md
app/Http/Controllers/System/UsersController.php
app/Http/Requests/System/CreateUser.php
app/Http/Requests/System/SaveUser.php
app/Http/Requests/System/UpdateUser.php
app/System/User.php
app/System/Users/LinuxUser.php
resources/js/components/System/UserEditor.vue
resources/js/store/modules/System/User.js
resources/sass/app.scss
resources/sass/pages/_system-users.scss
tests/Feature/Api/System/Users/CreateUserTest.php
tests/Feature/Api/System/Users/DeleteUserTest.php
tests/Feature/Api/System/Users/ListUsersTest.php
tests/Feature/Api/System/Users/UpdateUserTest.php

This adds support for creating custom or predefined home directories with a user, as well as moving and/or editing them after the user has been created.
Resolves #126.

Home directory support

---

CHANGELOG.md
app/Http/Controllers/System/GroupsController.php
app/Http/Controllers/System/UsersController.php
app/Http/Requests/System/CreateGroup.php
app/Http/Requests/System/CreateUser.php
app/Http/Requests/System/SaveGroup.php
app/Http/Requests/System/SaveUser.php
app/Http/Requests/System/UpdateGroup.php
app/System/Group.php
app/System/Groups/LinuxGroup.php
app/System/LinuxCommand.php
app/System/User.php
app/System/Users/LinuxUser.php
resources/js/components/System/GroupEditor.vue
resources/js/components/System/UserEditor.vue
resources/js/store/modules/System/User.js
tests/Feature/Api/System/Groups/CreateGroupTest.php
tests/Feature/Api/System/Users/CreateUserTest.php
tests/Feature/Api/System/Users/TestCase.php
tests/Feature/Api/System/Users/UpdateUserTest.php

Adds support for creating actual system users/groups, and setting user's shells.

Extra user options

---

CHANGELOG.md
app/FileManager/FileManager.php
app/Http/Controllers/FileController.php
app/Http/Middleware/TrimStrings.php
build/travis/script.sh
resources/js/components/Files/Browser/FileList.vue
resources/js/store/modules/FileManager.js
resources/test-skel/editme.txt
tests/Feature/Api/Files/ListFilesTest.php
tests/Feature/Api/Files/ShowFileTest.php
tests/Feature/Api/Files/UpdateFileTest.php
tests/Feature/Api/System/Groups/TestCase.php
tests/Feature/Api/System/Users/TestCase.php
tests/TestCase.php
tests/Unit/StatsBarTest.php

Cleans up general Files / File Manager code, adds a whole bunch of tests and fixes a couple minor bugs with saving files and listing non-existant directories.

Improvements to the File Manager

---

CHANGELOG.md
app/FileManager/FileManager.php
app/Http/Controllers/FileController.php
build/travis/prepare.sh
resources/js/components/Files/Browser/FileList.vue
resources/js/components/Files/Browser/FileRow.vue
resources/js/store/modules/FileManager.js
routes/api.php
tests/Feature/Api/Files/DeletePathTest.php

Adds a delete button to rows in the file browser so that files and folders can be deleted.
Fixes #214

Support file deletion

---

.github/scripts/install.sh
CHANGELOG.md
app/Databases/DatabaseData.php
app/Databases/DatabaseManager.php
app/Databases/TableCollection.php
app/Databases/TableData.php
app/Http/Controllers/Databases/ListDatabases.php
app/Http/Controllers/Databases/ShowDatabase.php
build/installer/_install.sh
build/php-cs-fixer/config.php
resources/js/components/Files/PathBar.vue
resources/js/pages/Databases.vue
resources/js/pages/Databases/DatabaseList.vue
resources/js/pages/Databases/DatabaseViewer.vue
resources/js/routes.js
resources/js/store/modules/Database.js
routes/api.php
setup.sh
tests/Feature/Api/Databases/ListDatabasesTest.php
tests/Feature/Api/Databases/ShowDatabaseTest.php
tests/Unit/Databases/DatabaseDataTest.php
tests/Unit/Databases/DatabaseManagerTest.php
tests/Unit/Databases/TableCollectionTest.php
tests/Unit/Databases/TableDataTest.php

* Adds default collation and charset as well as table count to the main Databases page
* Database rows can now be clicked through to get to the new details page
Details page currently consists of a tables list, where each table shows its row count, collation, charset and size.

Better databases

---

CHANGELOG.md
app/Projects/ProgressStep.php
app/Projects/Redirects/ApplyRedirectNginxConfig.php
app/Projects/ToggleProjectVisibility.php
resources/js/components/ProgressModal.vue
resources/js/components/Projects/Apps/DomainForm.vue
resources/js/components/Projects/Apps/RedirectForm.vue
resources/js/components/Projects/Apps/SourceSelector.vue
resources/js/components/Projects/ConfirmationForm.vue
resources/js/pages/Projects/NewProject.vue
resources/js/pages/Projects/steps.json
resources/js/store/modules/Progress.js
resources/js/store/modules/Project.js

Adds a bunch of improvements for the project Progress modal and fixes several bugs with error handling both in the modal and the form overall.
Resolves #387

Improve project progress and error handling

---

CHANGELOG.md
app/Http/Requests/Projects/NewProjectApp.php
app/Http/Requests/Projects/NewProjectRedirect.php
app/Projects/Application.php
app/Projects/Redirect.php
database/migrations/2022_12_02_213008_add_include_www_to_project_tables.php
resources/js/components/Projects/Apps/DomainForm.vue
resources/js/pages/Projects/NewProject.vue
resources/views/projects/app-templates/basic.blade.php
resources/views/projects/app-templates/php.blade.php
resources/views/projects/app-templates/redirect.blade.php
tests/Unit/Projects/RedirectTest.php

Adds a checkbox that'll enable an entry for `www.<the-domain>.com` when generating the nginx config's `server_name` line.

Add 'include www' checkbox on project domain page
