dshoreman/servidor

- app/Http/Controllers/System/GroupsController.php
- app/Http/Controllers/System/UsersController.php
- resources/js/app.js
- resources/js/components/MainMenu.vue
- resources/js/components/System/Groups.vue
- resources/js/components/System/Menu.vue
- resources/js/components/System/Users.vue
- resources/views/layouts/system.blade.php
- resources/views/system/groups.blade.php
- resources/views/system/users.blade.php
- routes/api.php
- routes/web.php
- tests/Feature/ListSystemGroupsTest.php
- tests/Feature/ListSystemUsersTest.php
Adds `GET` API endpoints for system users and groups (#19), with corresponding frontend list views.
Lists can be filtered, but there's no edit functionality yet.
> Add basic User/Group lists

- app/Http/Controllers/SiteController.php
- app/Site.php
- database/migrations/2018_10_07_010107_create_sites_table.php
- routes/api.php
- tests/Feature/CreateSiteTest.php
- tests/TestCase.php
Adds a basic Site model, migration and controller with ability to add, update and delete sites.
Implements most of #2, but for now only basic validation rules are applied.
> Add Sites API

- resources/js/components/Sites/Editor.vue
Moves the form tag to be above the header so that we can jam the
is_enabled toggle switch (technically a checkbox hence needing it in the
form) between it and the header. That way we can float it to the right
and it's kept out the way of the rest of the stuff.
Fixes #85.
> Add switch to change Sites' is_enabled flag

- app/Events/SiteUpdated.php
- app/Listeners/WriteSiteConfig.php
- app/Providers/EventServiceProvider.php
- app/Site.php
- resources/views/sites/server-templates/basic.blade.php
- resources/views/sites/server-templates/php.blade.php
- resources/views/sites/server-templates/redirect.blade.php
- tests/Feature/SitesApiTest.php
- vagrant/bootstrap.sh
When updating a Site/Application, this PR adds a selection of Blade templates with dummy Nginx configs. These are used to create the site's Nginx server config in `/etc/nginx/sites-available`. It will also clone the source repo into the document root, although there's no way of setting the branch currently.
Closes #58
Closes #62
> Maintain Nginx configs when changing Sites

- app/Http/Requests/UpdateSite.php
- app/Listeners/WriteSiteConfig.php
- app/Site.php
- database/migrations/2019_07_31_220427_add_source_repo_to_sites_table.php
- resources/js/components/Sites/Editor.vue
Splits the Clone URL field of the Site Editor into two columns so we can
add a new branch input next to it. Setting it doesn't do anything yet,
but this gets the groundwork laid (migration, validation etc) ready.
Closes #88.
> Add source branch field to Sites

- resources/js/pages/Sites.vue
- resources/js/store/modules/Site.js
This PR brings functionality from the System Users/Groups filter inputs with a few added extras that let you not only filter the list of Sites, but also open an existing one when you type in its name and hit enter.
Closes #61.
> Support filtering results from the Create Site box

- CHANGELOG.md
- resources/js/components/Sites/SiteItem.vue
- resources/js/pages/Files/Browser.vue
- resources/js/store/modules/Site.js
- resources/sass/_file-manager.scss
Replaces the not-so-pretty attached Manage Site button with normal links within an "extra card content" container.
This gives a much cleaner appearance and makes room for a new Browse Files button, which appears for sites with a document root and takes you to that place in the File Manager.
Also adds a corresponding button in the File Browser when the given path matches the document root of any sites to go directly to its editor page.
Closes #107.
> Add browse button to items in Sites list

- CHANGELOG.md
- resources/js/components/Files/Browser/FileList.vue
- resources/js/components/Files/Browser/FileRow.vue
Sets file icons to purple and folder icons to blue so that they can be easily distinguished.
If a symlink is encountered in a list, it'll inherit the colour of the thing it links to.
Closes #100.
> Icon colours

- vagrant/bootstrap.sh
Since upgrading the Vagrant box to the latest version of Ubuntu Bionic (18.04? Who knows), tests have been broken.
This is partly because the bootstrap script isn't creating the database, but it's also failing on anything with sudo since we're not automatically adding the sudoers entries.
This PR fixes all of the above.
> Fix tests in clean Vagrant environment

- .travis.yml
- CHANGELOG.md
- Vagrantfile
- app/FileManager/FileManager.php
- app/Http/Controllers/FileController.php
- resources/js/pages/Files/Editor.vue
- resources/js/store/modules/FileManager.js
- resources/test-skel/protected/forbidden
- tests/Unit/FileManager/FileManagerTest.php
Instead of displaying plain text error messages direct from PHP as the file's content, this PR replaces common errors with an icon and friendler message in a placeholder segment:
Fixes #102
> Handle errors when opening files

- CHANGELOG.md
- resources/js/pages/Files/Browser.vue
Before this PR if you went back from a file, browsed through a few folders then refreshed, you'd be back at whichever folder the file was in.
This tweaks the click handlers of file rows and the "up a level" button so that they update the URL to reflect the new file path every time the directory changes, meaning you can refresh at will without losing your place. Huzzah!
Fixes #99
> Set path in File Manager URLs when switching folders

- CHANGELOG.md
- app/Http/Requests/UpdateSite.php
- app/Rules/Domain.php
Makes the primary domain field required when updating a Site, and corrects the text of the error message.
Fixes #76
> Fix domain validation rule for Sites

- CHANGELOG.md
- resources/js/pages/Files/Browser.vue
- resources/sass/_file-manager.scss
Converts the plain-text path to a list of breadcrumbs, each of which is formatted as a link and can now be clicked on to jump to that point in the filesystem.
The dividers are also clickable, with the first (root) divider having some extra padding to give it a bigger click target. The last segment is deliberately made unclickable - probably don't need to do anything if we're already there.
Closes #106
> Make segments of path bar clickable in File Browser

- CHANGELOG.md
- app/StatsBar.php
- resources/js/components/StatsBar.vue
- tests/Unit/StatsBarTest.php
Adds disk usage item showing the root mountpoint and percent used of total. Also pulls the stats (except hostname/distro, which isn't really a stat) to the right to make it slightly easier on the eyes.
> Update stats bar

- CHANGELOG.md
- app/FileManager/FileManager.php
- resources/js/components/Files/Browser/FileRow.vue
- tests/Unit/FileManager/FileManagerTest.php
Octal form is still the default form shown in the file list, but now if you hover over it you'll get the textual *rwxrw-rw-* form in a tooltip.
Also normalises the octal forms to all be 4 digits. The mix of 3 and 4 digit permission strings was looking messy.
Closes #101
> Add tooltip with textual permissions

- .gitignore
- CHANGELOG.md
- app/Http/Controllers/SiteController.php
- resources/js/components/Sites/Editor.vue
- resources/js/components/Sites/SiteItem.vue
- resources/js/pages/Files/Browser.vue
- resources/js/pages/Sites/Detail.vue
- resources/js/routes.js
- resources/js/store/modules/Site.js
- routes/api.php
- tests/Feature/Api/SitesTest.php
Finally, we have a way to pull from Git without making some change so that it triggers the save events. Adds a details page to act as a dashboard of sorts, and updates links in the site list and file browser to go here instead of the editor.
Closes #91
> Site Details page with ability to trigger `git pull`

- CHANGELOG.md
- resources/js/components/Files/Browser/FileList.vue
- resources/js/components/Sites/Editor.vue
- resources/js/components/System/GroupEditor.vue
- resources/js/components/System/Groups.vue
- resources/js/components/System/UserEditor.vue
- resources/js/components/System/Users.vue
- resources/js/pages/Files/Browser.vue
- resources/js/pages/Files/Editor.vue
- resources/js/pages/Sites.vue
- resources/js/pages/Sites/Detail.vue
- resources/js/pages/Sites/Edit.vue
- resources/js/pages/Sites/List.vue
- resources/js/store/index.js
- resources/js/store/modules/FileManager.js
- resources/js/store/modules/Site.js
- resources/js/store/modules/System/Group.js
- resources/js/store/modules/System/User.js
Namespaces every VueX module with the exception of `Auth` because that's probably better off in the root namespace. At least now there's nothing left for it to conflict with...
Also taken the liberty of renaming some actions. Things like `createUser`, `updateSite` etc made sense before, but now we're prefixing with the module name it gets a bit dirty. `users/create` is far better than `users/createUser`.
Fixes #144.
> Namespace the VueX modules to isolate searches

- package-lock.json
- package.json
All major versions, so these won't be handled be @depfu.
The laravel-mix update is to support sass-loader which, like cross-env, removes support for old Node versions.
> Update Mix, Sass Loader and Cross-env

- resources/js/layouts/Servidor.vue
- resources/sass/_layout.scss
- resources/sass/layout/_footer.scss
- resources/views/layouts/app.blade.php
- resources/views/servidor.blade.php
I moved the footer over to vue where it seems to make more sense.
Since the footer is now technically a part of the `<section class="main>` section, I swapped `<footer>` with `<div class="version">` which was added to _layouts.scss. This made the most since to me at the time since it allows to add an actual "global" footer later using _footer.scss (which i left behind) and the `<footer>` tag.
Let me know how you feel about the changes or if you'd like to see this done another way.
Fixes #149
> Move version info to main app layout

- resources/js/pages/Files/Editor.vue
- resources/js/store/modules/FileManager.js
Before loading a new file the old file contents are now cleared.
Additionally I added loading state to the file viewer.
Fixes #118
> Fix Old file flickers before showing the current file #118 

- resources/js/components/Sites/Editor.vue
Solves bug where undefined would be showing in document root when primary domain isn't set.
Fixes #171
> Fix 'undefined' showing in document root

- CHANGELOG.md
- app/Http/Controllers/SiteController.php
- resources/js/components/Sites/Editor.vue
- resources/js/store/modules/Site.js
- routes/api.php
Adds a dropdown to the Site Editor that lists branches for selection instead of manually typing the name of a branch into an input. The options are updated any time the `source_repo` field is changed to make sure we're setting the branches from the right repository.
Branches are listed by running `git ls-remote` from a new API endpoint `GET sites/:id/branches`. The resulting dropdown can be filtered and will also show loading state while we're waiting for a response from the API.
Closes  #92
> Sites: Branch dropdown

- resources/js/pages/Files/Editor.vue
- resources/sass/components/_codemirror.scss
- resources/sass/pages/_file-manager.scss
Makes sure the file content isn't visible while the file is actually loading, and updates the height to be set on the parent to fix issues with height being different while loading.
> File editor fixup

- CHANGELOG.md
- app/FileManager/FileManager.php
- resources/js/pages/Files/Editor.vue
- tests/Unit/FileManager/FileManagerTest.php
Adds very basic support for checking a file's detected MIME type before attempting to get the contents of something we can't display, such as an image.
Closes #103
> File MIME checking

- CHANGELOG.md
- resources/js/components/Files/Browser/FileList.vue
- resources/js/components/Files/Browser/FileRow.vue
- resources/js/components/Files/PathBar.vue
- resources/js/pages/Files/Browser.vue
- resources/js/pages/Files/Editor.vue
This moves the file editor's path bar code into a new `PathBar` component which is now also used in the file viewer.
Initially I'd left the directory change handling bits in place, but with it being called from 3 or 4 places with largely the same code with the exception of slightly different paths it made sense to move those into the component too.
To support that, the `open` method in the file row has also been updated to handle opening directories instead of only files.
Fixes #185
> Split pathbar into linked segments on the file editor

- CHANGELOG.md
- resources/js/components/StatsBar.vue
- resources/js/pages/Auth/Login.vue
- resources/sass/pages/_login.scss
Fixes missing styles from the Blade to Vue conversion in the login page that caused the styles to not be loaded, and updates the `.column` rule to be more specific so that it gets applied.
Also converts the overall styling of the login page to match that of dark mode once logged in.
> Login page

- CHANGELOG.md
- app/Http/Controllers/SiteController.php
- app/Http/Requests/UpdateSite.php
- app/Listeners/WriteSiteConfig.php
- app/Site.php
- database/migrations/2020_09_19_211510_change_docroot_to_project_root_in_sites_table.php
- database/migrations/2020_09_19_213602_add_public_dir_column_to_sites_table.php
- resources/js/components/Sites/Editor.vue
- resources/js/components/Sites/SiteItem.vue
- resources/js/pages/Sites/Detail.vue
- resources/js/store/modules/Site.js
- resources/views/sites/server-templates/php.blade.php
- tests/Feature/Api/SitesTest.php
- tests/Unit/Http/Requests/UpdateSiteRequestTest.php
- tests/Unit/Listeners/WriteSiteConfigTest.php
- tests/Unit/SiteTest.php
This renames the `document_root` field to `project_root` to signify that it's not necessarily going to be the actual `root` used in its nginx server block. Instead, `document_root` is now an attribute getter that combines `project_root` with a new `public_dir` attribute. This should make it a lot easier to deal with cloning laravel or similar projects.
> Separate the public folder into its own field

- build/eslint/config.json
- package-lock.json
- package.json
- resources/js/app.js
- resources/js/components/StatsBar.vue
- resources/js/pages/Files/Editor.vue
- resources/js/pages/Sites/Detail.vue
- resources/js/store/modules/Auth.js
- resources/js/store/modules/Database.js
- resources/js/store/modules/FileEditor.js
- resources/js/store/modules/FileManager.js
- resources/js/store/modules/Site.js
- resources/js/store/modules/System/Group.js
- resources/js/store/modules/System/User.js
Updates the following packages...
- Update vue-router (3.4.4 => 3.4.5)
- Update semantic-ui-vue (0.8.1 => 0.11.0)
- Update axios (0.19.2 => 0.20.0)
- Update resolve-url-loader (3.1.0 => 3.1.1)
- Update cross-env (6.0.3 => 7.0.2)
- Update sass-loader (8.0.2 => 10.0.2)
- Update eslint-plugin-vue (6.2.2 => 7.0.0-beta.4)
- Update eslint (6.8.0 => 7.10.0)
...and bumps eslint to use es2020 syntax while enabling some new and previously ignored rules.
> Update dependencies and eslint rules

- Makefile
- README.md
- Vagrantfile
- build/installer/_install.sh
- setup.sh
This splits the Vagrant provisioning into a 3-step process to solve the issue with the servidor user needing to be created since we can't rely on IDs. When we're running in Vagrant, the installer will now skip user creation, leaving it to the `user` provisioner.
Issues with composer install are caused by a race condition due to a bug in Virtualbox, so to fix that we add the `--prefer-source` flag. That's incredibly slow though, so we also check for the existence of composer on the host and run it locally if possible via a new `dev-env` make target that will nuke all caches etc before reconstructing the whole environment.
Fixes #274
> Fix the installer when running in Vagrant

- resources/js/store/modules/FileEditor.js
Replaces `CodeMirror.findModeByExtension` with `CodeMirror.findModeByFileName` to detect nginx conf files properly.
If `findModeByFileName` doesn't match anything it automatically tries to find a match via `findModeByExtension`. If that fails to return info as well we try to determine a mode by calling `CodeMirror.findModeByMIME`.
This is the discussion + pr in the codemirror repo
https://github.com/codemirror/CodeMirror/issues/2940
https://github.com/codemirror/CodeMirror/pull/3027
Fixes #187
> Set file editor mode based on filename

- resources/js/pages/Files/Editor.vue
- resources/js/store/modules/FileEditor.js
- resources/sass/components/_codemirror.scss
This adds the following codemirror addons from #190:
- simplescrollbars
- active-line
- continuecomment
- matchbrackets
- closebrackets
- trailingspace (I ignored the idea with the ::before tag content because it only adds a single span for all trailing spaces and not a span per space)
- closetag
> Implement codemirror addons

- resources/js/plugins/darkmode/index.js
Inside the mixinx created hook we can check if the currentTheme is null (not set in localStorage) and then set it to the default value of 'light'
To my understanding this should always work as data should be fully initialized and reactive when the "created" hook is called.
Fixes #289
> Initialize `theme` in localStorage if unset

- .github/workflows/ci.yml
- README.md
This PR aims to fill some of the gaps left by the migration from TravisCI in #335.
**TODO:**
Resolves the first part of #340
> Better CI workflow notifications

- .github/workflows/ci.yml
- app/Http/Controllers/Auth/RegisterController.php
- app/Rules/Domain.php
- app/Rules/NoColon.php
- app/Rules/NoComma.php
- app/Rules/NoWhitespace.php
- build/php-cs-fixer/config.php
- build/phpmd/CamelCaseVariableName.php
- build/phpmd/rules.xml
- composer.json
Adds a new rule for PHPMD so that we can allow `$_` in variable names
without suppressing the `CamelCaseVariableName` entirely, and adds an
exception for the `UnusedLocalVariable` rule so it doesn't complain.
Phan was failing in GH Actions due to lack of **php-ast**, so that has
been added to the `setup-php` job in our workflow. We also ignore the
**node_modules** directory for PHP CS Fixer to stop it spewing errors
within some random PHP files included from some random npm package.
Fixes #351.
> Fix PHPMD, Phan and PHP CS Fixer

- .gitignore
- composer.json
- composer.lock
- config/clockwork.php
Adds support for https://underground.works/clockwork with basically everything enabled except the toolbar and `/clockwork` web-app route.
> Enable Clockwork extension for devtools

- .github/workflows/ci.yml
- Makefile
- app/Database.php
- app/Http/Requests/System/CreateUser.php
- composer.json
- composer.lock
- config/app.php
Fixues a bunch of "null as string" deprecation errors in PHP 8.1, and updates dependencies to latest.
Both laravel/framework and laravel/sanctum throw deprecation warnings that get transformed into exceptions in tests. Forked and fixed, but PRs currently pending.
* **PR:** laravel/framework#36622 (merged in [v8.34.0][1])
Triggers the warning when messages for a validation rule are formatted, and `getDisplayableValue()` returns `null` when it's passed to `str_replace()`.
* **PR:** laravel/sanctum#258 (merged in [v2.9.1][2])
Triggers it in the `EnsureFrontendRequestsAreStateful` middleware when a request lacks both a `Referer` and an `Origin` header. This breaks all tests that hit frontend routes.
---
Laravel also threw warnings on 6.x (or just 7? need to double check) for any routes …
> PHP 8.1 Support

- build/hooks/pre-commit.sh
I have a horrible habit of using git add --patch to partially stage
files, committing a big batch of changes in chunks that make sense.
Unfortunately, that causes havoc with the idea of stashing, fixing and
popping automatically before commit. In reality, it will often stash,
apply fixes, then throw its toys out the pram with a merge conflict.
A lot of the time, this results in committing changes that were unstaged
previously, as the conflict resolution screws up what was staged before.
This PR hopefully fixes the issue without risking loss of other changes.
> Fix pre-commit autofixing of PHP files

- CHANGELOG.md
- resources/js/app.js
Since the `loggedIn` getter relies on there being a `user` object saved
in SessionStorage, opening links in a new tab results in a redirect back
to /login, even though the session may still be active and usable.
This resolves the issue by first attempting to re-fetch the profile
(which will set the `user` object back in SessionStorage) but *only*
when we're trying to fetch an authed page while seemingly "not authed".
> Fix login being required in new tabs

- CHANGELOG.md
- resources/js/pages/Projects/NewProject.vue
We previously moved everything into a single Promise.all to stop eslint
complaining about being one line over the max statements rule, but that
prevents the progress/monitor promise from using the `project` value.
This moves the primary project creation promise back into its own line
so that project is assigned first, then the rest can run normally.
> Fix Promise.all() being too greedy

- app/Projects/Application.php
- app/Projects/Applications/DeployApp.php
- app/Projects/Applications/ProjectAppSaved.php
- app/Projects/Applications/Templates/Html.php
- app/Projects/Applications/Templates/Template.php
- app/Projects/Redirect.php
- app/Projects/Redirects/ApplyRedirectNginxConfig.php
- app/Projects/Redirects/ProjectRedirectSaved.php
- app/Projects/ToggleProjectVisibility.php
- app/Providers/EventServiceProvider.php
Previously enabling a project was part of the template's `pullCode`
method, which had to take a bool parameter to know if it should be
enabled automatically or not.
This PR moves both the enable and disable code into a new
`ToggleProjectVisibility` handler to simplify pull/deploy.
Closes #384.
> Consolidate app/redirect {en,dis}able handling

- .github/workflows/release.yml
- CHANGELOG.md
GitHub [no longer shows tags](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#the-papercuts-smaller-improvements) in the Releases list, so this adds a new workflow that will extract the matching version's changes from the changelog and use them to create a new release.
> Auto-create releases from tags using the changelog

- app/Databases/DatabaseCollection.php
- app/Databases/DatabaseDTO.php
- app/Databases/DatabaseManager.php
- app/Databases/TableCollection.php
- app/Databases/TableCollectionCaster.php
- app/Databases/TableDTO.php
- app/Http/Controllers/Databases/CreateDatabase.php
- app/Http/Controllers/Databases/ShowDatabase.php
- build/phan/config.php
- build/phpinsights/config.php
- composer.json
- composer.lock
- tests/Unit/Databases/DatabaseCollectionTest.php
- tests/Unit/Databases/DatabaseDTOTest.php
- tests/Unit/Databases/DatabaseManagerTest.php
- tests/Unit/Databases/TableCollectionTest.php
- tests/Unit/Databases/TableDTOTest.php
This adds spatie/data-transfer-object to the project and uses it for `DatabaseData` and `TableData` (where `Data` is now `DTO`).
The `DatabaseManager::tables()` method is also renamed to `databaseWithTables()`. Rather than returning a `TableCollection` for the user/backend to manually load into a `DatabaseDTO`, it'll simply return a copy of the given database with tables preloaded.
> Refactor database/table DTOs to Spatie implementation

- CHANGELOG.md
- Makefile
- build/installer/_prepare.sh
- setup.sh
Seems the php repo now defaults to 8.1 for the php package, and pcov
must've slipped the net when all the others were defined. Installing
`php-pcov` causes PHPUnit to show a 'coverage not available' warning
since phpunit will be running under 8.0, but pcov is only under 8.1.
This adds *both* PHP 8.0 *and* PHP 8.1 to the installer.
> Fix php-pcov package version

- CHANGELOG.md
- app/Projects/Project.php
- app/Projects/ProjectSaved.php
- app/Projects/ToggleProjectVisibility.php
- app/Providers/EventServiceProvider.php
- resources/views/projects/app-templates/php.blade.php
- tests/Feature/Api/Projects/Applications/PullCodeTest.php
- tests/Feature/Api/Projects/RemoveProjectTest.php
- tests/Feature/Api/Projects/UpdateProjectTest.php
Adds a `ProjectSaved` event on the Project model so we can dispatch the required actions/jobs/tasks to add/remove the symlink in `nginx/sites-enabled` and reload nginx.
Also fixes the PHP version used in the default nginx template. Previously it was 7.4 which wasn't installed, so it threw a 502 Bad Gateway on and PHP or Laravel projects.
> Fix nginx symlink not being toggled on Project save

- CHANGELOG.md
- resources/js/components/Projects/Apps/RedirectForm.vue
- resources/js/pages/Projects/NewProject.vue
- resources/js/pages/Projects/steps.json
- resources/views/projects/app-templates/redirect.blade.php
- tests/Unit/Projects/RedirectTest.php
Moves the redirect type dropdown to the top of the form alongside a new
'Rule Template' dropdown with options for either custom or WBM archives.
With this, the fields related to WayBack Machine archive date/time now
use the full form width and will not be visible if 'Custom' is chosen.
Also makes the appending of `$request_uri` settable, and adds a rule
preview.
> Add dropdown to choose between custom or archive

- CHANGELOG.md
- app/Http/Requests/Projects/NewProjectApp.php
- app/Projects/Application.php
- database/migrations/2023_01_08_201926_add_config_to_project_applications.php
- resources/js/components/Projects/Apps/PhpVersions.vue
- resources/js/components/Projects/Viewer/ProjectLogs.vue
- resources/js/pages/Projects/NewProject.vue
- resources/js/pages/Projects/ProjectViewer.vue
- resources/js/pages/Projects/steps.json
- resources/js/pages/Projects/templates.json
- resources/views/projects/app-templates/php.blade.php
- tests/Unit/Http/Requests/NewProjectAppTest.php
- tests/ValidatesFormRequest.php
Adds a config field to the `project_applications` table for extra project app data, which enables us to easily add a PHP Version dropdown in the creation wizard.
That option (for PHP/Laravel projects) is then used to set the fpm version in the nginx config, and will be shown in the Project Viewer as a label at the top-right of the source details.
> Add ability to set PHP version per-project

- CHANGELOG.md
- resources/js/pages/Projects/NewProject.vue
- resources/js/pages/Projects/ProjectViewer.vue
Fixes values not being reset on discard in the creation wizard.
Also fixes the logs header not being shown on the viewer when a project has logs, which would cause the log viewer component to "nest" with the system user or whichever component happened to be above it.
> Fix some frontend bugs in Projects

- app/Http/Requests/Projects/NewProjectApp.php
- app/Http/Requests/Projects/NewProjectRedirect.php
- resources/js/components/Projects/Apps/DomainForm.vue
- resources/js/pages/Projects/NewProject.vue
- resources/views/projects/app-templates/basic.blade.php
- resources/views/projects/app-templates/php.blade.php
- tests/Feature/Api/Projects/Applications/NginxConfigGenerationTest.php
- tests/Feature/Api/Projects/nginx-configs/basic.nossl.any-www.conf
- tests/Feature/Api/Projects/nginx-configs/basic.nossl.no-www.conf
- tests/Feature/Api/Projects/nginx-configs/php.nossl.any-www.conf
- tests/Feature/Api/Projects/nginx-configs/php.nossl.force-www.conf
- tests/Feature/Api/Projects/nginx-configs/php.nossl.no-www.conf
- tests/Feature/Api/Projects/nginx-configs/php.nossl.strip-www.conf
Adds a new dropdown to the domain form where a user can define whether the domain should have the "www." forced, removed, or "prefix agnostic".
Also adds a test to make sure the generated configs are as we'd actually expect, although there aren't any for SSL sites so that's one thing that could be improved in future if there are ever any issues with it.
> Add option for forcing a www-prefix preference

- .github/workflows/ci.yml
- CHANGELOG.md
- app/Projects/Applications/ApplyAppNginxConfig.php
- app/Projects/Applications/CreateSystemUser.php
- app/Projects/Applications/DeployApp.php
- app/Projects/Applications/PrepareSsl.php
- app/Projects/CalculateSteps.php
- app/Projects/ReloadNginxService.php
- app/Providers/EventServiceProvider.php
- resources/js/pages/Projects/NewProject.vue
- resources/js/store/modules/Progress.js
When saving a new project with an application of some sort (not a
redirect), many of the events won't have their step added despite the
event itself still being sent through Pusher.
This updates the affected "jobs" to trigger the start progress event,
which gives the progress modal a bit of a kick up the rear, and also
updates modal to show steps sooner and with more reliable progress.
> Fix steps not being added on project creation

- CHANGELOG.md
- database/migrations/2023_02_15_164426_merge_applications_and_redirects_to_services_table.php
- tests/Feature/Api/Projects/RemoveProjectTest.php
Adds `ON DELETE CASCADE` to the foreign key constraint so that projects no longer trigger an error when you try to delete one with an app.
> Fix issue where projects can't be deleted

- CHANGELOG.md
- app/Http/Controllers/User/UpdateAccount.php
- resources/js/components/Projects/Services/DomainForm.vue
- resources/js/layouts/Servidor.vue
- resources/js/pages/Auth/AccountEditor.vue
- resources/js/routes.js
- resources/js/store/modules/Auth.js
- resources/sass/layout/_sidebar.scss
- routes/api.php
- tests/Feature/Api/User/UpdateAccountTest.php
- tests/RequiresAuth.php
Adds a new page, accessible via 'Account Settings' in the bottom-left menu, with two forms for changing the account password or name and email.
A much needed addition, and saves me having to worry about replacing the default user seeder with something more practical in the installer.
> Add basic Account Settings page

- build/installer/_install.sh
- build/installer/_templates.sh
Adds `servidor.service` to /lib/systemd/system so the `queue:work` artisan command can be started—and kept alive—with systemd commands.
The service is enabled and started by default so there should no longer be any need to manually start anything with `vagrant ssh -c 'cd /var/servidor && php artisan queue:work'`.
> Auto-install a systemd unit to process the queue

- CHANGELOG.md
- app/Projects/Actions/SaveSslCertificate.php
- tests/Feature/Api/Projects/Actions/SaveSslCertTest.php
This fixes an issue where you could create a project with an SSL certificate and both the cert+key would save correctly into the certs dir, but the paths weren't being saved in the model's config Collection.
> Fix project config not saving correctly for SSL

- CHANGELOG.md
- resources/js/components/ProgressModal.vue
- resources/js/components/Projects/ConfirmationForm.vue
- resources/js/components/Projects/Services/DomainForm.vue
- resources/js/components/Projects/Services/PhpVersions.vue
- resources/js/components/Projects/Services/RedirectForm.vue
- resources/js/components/Projects/Services/SourceSelector.vue
- resources/js/components/Projects/Services/SslForm.vue
- resources/js/components/Projects/Services/TemplateSelector.vue
- resources/js/components/Projects/StepButtons.vue
- resources/js/components/Projects/StepList.vue
- resources/js/pages/Projects/NewProject.vue
- resources/js/pages/Projects/ProjectList.vue
- resources/js/pages/Projects/source-providers.json
- resources/js/store/modules/Progress.js
- resources/sass/themes/darkmode-custom.scss
Applies the inverted attribute to all project creation forms and adds
some extra styles for the steps, dropdowns and checkbox toggle switches.
For buttons, positive is replaced with `color="green"` in dark mode
because the inverted positive is an ugly white-bordered green button and
I'm too lazy to just make it look more like the positive primary button.
Also fixes the placeholder segment on the main project list page.
> Fixes various dark-mode bugs in Projects
